// Code generated by go-swagger; DO NOT EDIT.

package posttest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// PosttestURL generates an URL for the posttest operation
type PosttestURL struct {
	Enum *string
	Num  *int32
	Str  *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PosttestURL) WithBasePath(bp string) *PosttestURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PosttestURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *PosttestURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/posttest"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var enumQ string
	if o.Enum != nil {
		enumQ = *o.Enum
	}
	if enumQ != "" {
		qs.Set("enum", enumQ)
	}

	var numQ string
	if o.Num != nil {
		numQ = swag.FormatInt32(*o.Num)
	}
	if numQ != "" {
		qs.Set("num", numQ)
	}

	var strQ string
	if o.Str != nil {
		strQ = *o.Str
	}
	if strQ != "" {
		qs.Set("str", strQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *PosttestURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *PosttestURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *PosttestURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on PosttestURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on PosttestURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *PosttestURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
