// Code generated by go-swagger; DO NOT EDIT.

package posttest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PosttestHandlerFunc turns a function with the right signature into a posttest handler
type PosttestHandlerFunc func(PosttestParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PosttestHandlerFunc) Handle(params PosttestParams) middleware.Responder {
	return fn(params)
}

// PosttestHandler interface for that can handle valid posttest params
type PosttestHandler interface {
	Handle(PosttestParams) middleware.Responder
}

// NewPosttest creates a new http.Handler for the posttest operation
func NewPosttest(ctx *middleware.Context, handler PosttestHandler) *Posttest {
	return &Posttest{Context: ctx, Handler: handler}
}

/* Posttest swagger:route GET /posttest posttest posttest

for Post API test

*/
type Posttest struct {
	Context *middleware.Context
	Handler PosttestHandler
}

func (o *Posttest) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPosttestParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
