// Code generated by go-swagger; DO NOT EDIT.

// Package restapi sample
//
//  Golang Server API
//  Schemes:
//    http
//  Host: localhost:8000
//  BasePath: /v1
//  Version: 1.0.0
//  License: MIT
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
