// Code generated by go-swagger; DO NOT EDIT.

package gettest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GettestHandlerFunc turns a function with the right signature into a gettest handler
type GettestHandlerFunc func(GettestParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GettestHandlerFunc) Handle(params GettestParams) middleware.Responder {
	return fn(params)
}

// GettestHandler interface for that can handle valid gettest params
type GettestHandler interface {
	Handle(GettestParams) middleware.Responder
}

// NewGettest creates a new http.Handler for the gettest operation
func NewGettest(ctx *middleware.Context, handler GettestHandler) *Gettest {
	return &Gettest{Context: ctx, Handler: handler}
}

/* Gettest swagger:route GET /gettest gettest gettest

for Get API test

*/
type Gettest struct {
	Context *middleware.Context
	Handler GettestHandler
}

func (o *Gettest) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGettestParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
