name: Build
on: [push]
jobs:
  build-server:
    name: Build and Test server
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build code
        run: |
          cd src
          go build

      - name: Test code
        run: |
          cd src
          go test ./...
