// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Obj obj
//
// swagger:model Obj
type Obj struct {

	// id
	// Required: true
	ID *int64 `json:"id"`

	// name
	// Required: true
	Name *string `json:"name"`

	// value
	// Required: true
	// Enum: [foo bar]
	Value *string `json:"value"`
}

// Validate validates this obj
func (m *Obj) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Obj) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *Obj) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

var objTypeValuePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["foo","bar"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		objTypeValuePropEnum = append(objTypeValuePropEnum, v)
	}
}

const (

	// ObjValueFoo captures enum value "foo"
	ObjValueFoo string = "foo"

	// ObjValueBar captures enum value "bar"
	ObjValueBar string = "bar"
)

// prop value enum
func (m *Obj) validateValueEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, objTypeValuePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Obj) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	// value enum
	if err := m.validateValueEnum("value", "body", *m.Value); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this obj based on context it is used
func (m *Obj) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Obj) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Obj) UnmarshalBinary(b []byte) error {
	var res Obj
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
